logging:
  config: classpath:logback-spring-dev.xml

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:10001/eureka/
    # 表示是否将自己注册到eureka server
    register-with-eureka: true
    # 表示是否从eureka server获取注册的服务信息
    fetch-registry: true
  instance:
    # 以IP地址注册到服务中心，相互注册使用IP地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sc-bus?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 0
      maximum-pool-size: 8
      idle-timeout: 180000
  jpa:
    hibernate:
      # 每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database: mysql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/sc-bus