spring:
  application:
    name: BUS-MANAGER
  profiles:
    active: local
server:
  port: 9002

mybatis:
  # mapper文件路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 驼峰自动映射
    map-underscore-to-camel-case: true